"""
ClarityLoop – Demo Mode Seed Data
Seeds the database with rich demo content for all major features.
Works without an OpenAI API key.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone

from app.db.session import AsyncSessionLocal
from app.models.user import User, UserPreference, ResourceProfile
from app.models.project import Project
from app.models.conversation import Conversation, Branch, Message
from app.models.task import Task, TaskDependency
from app.models.evidence import Evidence, Claim
from app.models.assumption import Assumption
from app.models.feasibility import FeasibilityAssessment, AssessmentVersion
from app.models.decision import Decision
from app.models.canvas import WorkflowNode, WorkflowEdge
from app.models.focus import FocusSession


DEMO_NOTICE = "\n\n---\n*⚠️ Demo responses are mocked and are not generated by a live AI model.*"

DEMO_USER_ID = "demo-user"
DEMO_PROJECT_1 = "demo-proj-feasible"
DEMO_PROJECT_2 = "demo-proj-conditional"
DEMO_PROJECT_3 = "demo-proj-infeasible"


async def seed_demo_data() -> None:
    """Idempotent demo data seeder. Safe to call multiple times."""
    async with AsyncSessionLocal() as db:
        # Check if already seeded
        from sqlalchemy import select
        result = await db.execute(select(User).where(User.id == DEMO_USER_ID))
        if result.scalar_one_or_none():
            return  # Already seeded

        # ── User ─────────────────────────────────────────────────────────────
        user = User(
            id=DEMO_USER_ID,
            username="demo_user",
            display_name="Demo User",
        )
        db.add(user)

        default_user = User(
            id="default-user",
            username="local_user",
            display_name="Local User",
        )
        db.add(default_user)

        pref = UserPreference(
            user_id=DEMO_USER_ID,
            answer_depth="adaptive",
            skill_level="intermediate",
            theme="dark",
        )
        db.add(pref)

        resource = ResourceProfile(
            user_id=DEMO_USER_ID,
            cpu_cores=8,
            ram_gb=16.0,
            gpu_model="No dedicated GPU",
            storage_gb=500.0,
            operating_system="Windows 11",
            monthly_budget_usd=0.0,
        )
        db.add(resource)
        await db.flush()

        # ── Project 1: Feasible ───────────────────────────────────────────────
        p1 = Project(
            id=DEMO_PROJECT_1,
            user_id=DEMO_USER_ID,
            title="Build a personal recipe recommendation app",
            description="Create a web app that recommends recipes based on available ingredients",
            objective="Build a working recipe recommendation system using open-source tools",
            current_verdict="feasible",
            progress_pct=45,
            status="active",
            is_demo=True,
        )
        db.add(p1)

        # Project 1 conversation
        conv1 = Conversation(
            id="demo-conv-1",
            project_id=DEMO_PROJECT_1,
            user_id=DEMO_USER_ID,
            title="Recipe recommendation app feasibility",
            mode="feasibility",
            is_demo=True,
        )
        db.add(conv1)

        msg1 = Message(
            conversation_id="demo-conv-1",
            role="user",
            content="Can I build a recipe recommendation app that suggests meals based on ingredients I have at home? I have 16GB RAM, no GPU, and 8 weeks.",
            routing_mode="feasibility",
            is_demo=True,
        )
        db.add(msg1)
        await db.flush()

        msg2 = Message(
            conversation_id="demo-conv-1",
            role="assistant",
            content="""## Feasibility Assessment: Recipe Recommendation App

**Verdict: ✅ Feasible**
**Confidence: 78%** (High)

### What We Verified
- Open-source recipe datasets (e.g., Recipe1M+) are publicly available
- Content-based filtering works without a GPU on 16GB RAM
- 8-week timeline is achievable for a prototype

### Key Assumptions
- You will use Python + FastAPI backend
- Dataset: Open Recipes dataset (license verified: CC BY 4.0)
- ML approach: TF-IDF + cosine similarity (no GPU needed)

### Recommended Next Action
Start with the dataset download and set up your Python environment.
""" + DEMO_NOTICE,
            routing_mode="feasibility",
            confidence_score=0.78,
            has_feasibility=True,
            is_demo=True,
        )
        db.add(msg2)

        # Project 1 tasks
        t1 = Task(
            id="demo-task-1",
            project_id=DEMO_PROJECT_1,
            title="Set up Python environment",
            description="Install Python 3.11+, create virtual environment, install dependencies",
            phase="Phase 1: Setup",
            expected_output="Running Python environment with FastAPI installed",
            completion_condition="Running `uvicorn --version` returns a version number",
            status="completed",
            priority=10,
            is_primary_next=False,
            order_index=0,
            is_demo=True,
            completed_at=datetime.now(timezone.utc),
        )
        db.add(t1)

        t2 = Task(
            id="demo-task-2",
            project_id=DEMO_PROJECT_1,
            title="Download and explore recipe dataset",
            description="Download Open Recipes dataset, explore structure, check labels",
            phase="Phase 1: Setup",
            expected_output="Dataset loaded into Pandas DataFrame with ingredient columns visible",
            completion_condition="Can print the first 5 recipes with ingredients",
            status="in_progress",
            priority=9,
            is_primary_next=True,
            order_index=1,
            is_demo=True,
        )
        db.add(t2)

        t3 = Task(
            id="demo-task-3",
            project_id=DEMO_PROJECT_1,
            title="Build ingredient-to-recipe matching",
            description="Implement TF-IDF vectorization for ingredient matching",
            phase="Phase 2: Core Logic",
            status="not_started",
            priority=8,
            order_index=2,
            is_demo=True,
        )
        db.add(t3)

        t4 = Task(
            id="demo-task-4",
            project_id=DEMO_PROJECT_1,
            title="Build FastAPI backend",
            status="not_started",
            priority=7,
            order_index=3,
            is_demo=True,
        )
        db.add(t4)
        await db.flush()

        # Task dependencies
        dep1 = TaskDependency(task_id="demo-task-3", depends_on_id="demo-task-2")
        dep2 = TaskDependency(task_id="demo-task-4", depends_on_id="demo-task-3")
        db.add_all([dep1, dep2])

        # Project 1 assumptions
        a1 = Assumption(
            project_id=DEMO_PROJECT_1,
            statement="16 GB RAM is sufficient",
            category="hardware",
            current_value="16 GB",
            impact="TF-IDF on 1M recipes requires ~4GB RAM peak",
        )
        a2 = Assumption(
            project_id=DEMO_PROJECT_1,
            statement="No dedicated GPU",
            category="hardware",
            current_value="No GPU",
            impact="Limits to non-deep-learning approaches; TF-IDF works without GPU",
        )
        a3 = Assumption(
            project_id=DEMO_PROJECT_1,
            statement="8-week deadline",
            category="time",
            current_value="8 weeks",
            impact="Sufficient for a prototype; not enough for production-grade UI",
        )
        db.add_all([a1, a2, a3])

        # Project 1 evidence
        ev1 = Evidence(
            project_id=DEMO_PROJECT_1,
            title="Open Recipes Dataset",
            url="https://archive.org/details/recipes-en-201706",
            source_org="Archive.org",
            source_type="repository",
            source_quality=4,
            source_quality_reason="Established data platform with clear licence documentation",
            supported_claim="Large recipe dataset is freely available",
            summary="~1M English recipes with ingredients and instructions. CC BY 4.0 licence.",
            reliability="high",
            verification_status="verified",
            is_demo=True,
        )
        db.add(ev1)

        # Project 1 feasibility assessment
        fa1 = FeasibilityAssessment(
            project_id=DEMO_PROJECT_1,
            verdict="feasible",
            confidence_score=0.78,
            confidence_explanation="Critical resources verified: dataset exists, licence confirmed, hardware sufficient for TF-IDF approach.",
            verified_requirements=json.dumps(["Python 3.11", "Recipe dataset", "TF-IDF library"]),
            blockers_json=json.dumps([]),
            risks_json=json.dumps(["Dataset may have inconsistent ingredient formatting"]),
            realistic_alternative=None,
            what_would_make_feasible=json.dumps(["Already feasible"]),
            recommended_next_action="Download the dataset and run a quick data exploration",
            review_rounds=1,
            agents_used=json.dumps(["requirement_analyst", "evidence_researcher", "resource_assessor", "skeptic", "final_judge"]),
            is_demo=True,
        )
        db.add(fa1)
        await db.flush()

        v1 = AssessmentVersion(
            assessment_id=fa1.id,
            version_number=1,
            verdict="feasible",
            confidence_score=0.78,
            change_reason="Initial assessment",
        )
        db.add(v1)

        # ── Project 2: Conditionally Feasible ────────────────────────────────
        p2 = Project(
            id=DEMO_PROJECT_2,
            user_id=DEMO_USER_ID,
            title="Train medical image classifier for 20 conditions",
            description="Build a CNN model to classify 20 medical conditions from chest X-rays",
            objective="Clinical-grade medical image classification",
            current_verdict="feasible_with_conditions",
            progress_pct=15,
            status="active",
            is_demo=True,
        )
        db.add(p2)

        fa2 = FeasibilityAssessment(
            project_id=DEMO_PROJECT_2,
            verdict="feasible_with_conditions",
            confidence_score=0.42,
            confidence_explanation="Significant scope reduction required. Original 20-condition clinical goal is not feasible; a 5-condition research prototype is achievable.",
            verified_requirements=json.dumps(["CheXpert dataset (partial)", "GPU (required)"]),
            blockers_json=json.dumps([
                "No dedicated GPU — GPU required for CNN training",
                "Clinical validation requires regulatory approval not in scope",
                "20-condition dataset with verified labels not publicly available",
            ]),
            risks_json=json.dumps([
                "Data imbalance across conditions",
                "Domain shift between training and clinical data",
            ]),
            realistic_alternative="Classify 5 common conditions as a research prototype using CheXpert public split. No clinical reliability claims.",
            what_would_make_feasible=json.dumps([
                "Access to a GPU with at least 8GB VRAM",
                "Full CheXpert or NIH ChestX-ray14 dataset licence",
                "IRB approval for clinical validation",
                "Additional 12+ weeks",
            ]),
            recommended_next_action="Decide: accept 5-condition prototype, or acquire GPU access first",
            review_rounds=2,
            scope_change_approved=None,
            agents_used=json.dumps(["requirement_analyst", "evidence_researcher", "resource_assessor", "skeptic", "scope_agent", "final_judge"]),
            is_demo=True,
        )
        db.add(fa2)
        await db.flush()

        v2 = AssessmentVersion(
            assessment_id=fa2.id,
            version_number=1,
            verdict="feasible_with_conditions",
            confidence_score=0.42,
            change_reason="Initial assessment with scope reduction",
        )
        db.add(v2)

        # Scope change assumptions for project 2
        a4 = Assumption(
            project_id=DEMO_PROJECT_2,
            statement="Target: 20 medical conditions",
            category="scope",
            current_value="20 conditions",
            previous_value=None,
            impact="Requires full CheXpert dataset + clinical validation — not feasible without GPU and regulatory approval",
            needs_reanalysis=False,
            is_demo=True,
        )
        db.add(a4)

        # ── Project 3: Not Feasible ──────────────────────────────────────────
        p3 = Project(
            id=DEMO_PROJECT_3,
            user_id=DEMO_USER_ID,
            title="Real-time autonomous trading bot with 95% accuracy",
            current_verdict="not_feasible",
            progress_pct=0,
            status="active",
            is_demo=True,
        )
        db.add(p3)

        fa3 = FeasibilityAssessment(
            project_id=DEMO_PROJECT_3,
            verdict="not_feasible",
            confidence_score=0.15,
            confidence_explanation="Multiple critical blockers: accuracy claim unsupported by any published research, real-time requirements need co-location hardware, regulatory compliance not addressed.",
            verified_requirements=json.dumps([]),
            blockers_json=json.dumps([
                "95% trading accuracy is not demonstrated in any peer-reviewed research",
                "Real-time order execution requires co-location hardware ($thousands/month)",
                "Algorithmic trading regulation requires compliance with financial authorities",
                "Historical data for training is expensive or not freely available",
            ]),
            risks_json=json.dumps(["Financial loss risk if deployed with unvalidated strategy"]),
            realistic_alternative="Build a backtesting simulator that tests trading rules on historical data, making no live trading claims.",
            what_would_make_feasible=json.dumps([
                "Remove the 95% accuracy claim — no model achieves this consistently",
                "Start with paper trading (simulated) only",
                "Acquire proper financial data licences",
                "Consult a financial regulatory expert",
            ]),
            recommended_next_action="Reconsidering the core premise: set a realistic accuracy target and start with backtesting only",
            review_rounds=2,
            agents_used=json.dumps(["requirement_analyst", "evidence_researcher", "resource_assessor", "skeptic", "scope_agent", "final_judge"]),
            is_demo=True,
        )
        db.add(fa3)
        await db.flush()

        # ── Branch example (for project 1) ───────────────────────────────────
        branch1 = Branch(
            id="demo-branch-1",
            project_id=DEMO_PROJECT_1,
            title="Explore: Add dietary preference filtering",
            purpose="explore",
            inherited_summary="Project goal: recipe recommendation app. Currently in Phase 1 setup.",
            local_summary="Exploring how to add vegan/gluten-free filtering to the recommendation engine.",
            status="active",
            depth=1,
            is_demo=True,
        )
        db.add(branch1)

        branch2 = Branch(
            id="demo-branch-2",
            project_id=DEMO_PROJECT_1,
            parent_branch_id="demo-branch-1",
            title="Challenge: Will TF-IDF handle dietary labels?",
            purpose="challenge",
            inherited_summary="Exploring dietary filtering. Parent: recipe recommendation app.",
            status="active",
            depth=2,
            is_demo=True,
        )
        db.add(branch2)

        # Branch messages
        bm1 = Message(
            branch_id="demo-branch-1",
            role="user",
            content="Can we add vegan and gluten-free filtering to the recommendation system?",
            is_demo=True,
        )
        db.add(bm1)
        await db.flush()

        bm2 = Message(
            branch_id="demo-branch-1",
            role="assistant",
            content="""Yes! The Open Recipes dataset includes dietary tags for most recipes.

**Approach:**
1. During preprocessing, extract `vegan`, `gluten-free`, and `vegetarian` flags
2. Add a filter step before the TF-IDF ranking
3. Show only recipes matching the user's selected preferences

**Limitation:** About 30% of recipes lack dietary metadata, so results may be incomplete for niche diets.

**Estimated effort:** 2-3 additional hours on top of the base implementation.""" + DEMO_NOTICE,
            is_demo=True,
        )
        db.add(bm2)

        # ── Focus Session example ─────────────────────────────────────────────
        focus1 = FocusSession(
            user_id=DEMO_USER_ID,
            project_id=DEMO_PROJECT_1,
            task_id="demo-task-2",
            current_action="Download the Open Recipes dataset and open it in Python",
            why_it_matters="You need data before you can build the recommendation engine",
            expected_result="A Python script that prints the first 5 recipes",
            stuck_count=0,
            is_active=False,
            exit_reason="completed",
        )
        db.add(focus1)

        # ── Workflow Canvas nodes ─────────────────────────────────────────────
        n1 = WorkflowNode(project_id=DEMO_PROJECT_1, node_type="conversation", label="Initial Feasibility Chat", ref_id="demo-conv-1", ref_type="conversation", pos_x=100, pos_y=100)
        n2 = WorkflowNode(project_id=DEMO_PROJECT_1, node_type="completed", label="✅ Setup Python Environment", ref_id="demo-task-1", ref_type="task", pos_x=400, pos_y=100)
        n3 = WorkflowNode(project_id=DEMO_PROJECT_1, node_type="task", label="🔄 Download Dataset", ref_id="demo-task-2", ref_type="task", pos_x=700, pos_y=100)
        n4 = WorkflowNode(project_id=DEMO_PROJECT_1, node_type="task", label="Build Matching Logic", ref_id="demo-task-3", ref_type="task", pos_x=700, pos_y=250)
        n5 = WorkflowNode(project_id=DEMO_PROJECT_1, node_type="evidence", label="Open Recipes Dataset (CC BY 4.0)", ref_type="evidence", pos_x=400, pos_y=300)
        n6 = WorkflowNode(project_id=DEMO_PROJECT_1, node_type="conversation", label="Branch: Dietary Filtering", ref_id="demo-branch-1", ref_type="branch", pos_x=1000, pos_y=100)
        db.add_all([n1, n2, n3, n4, n5, n6])
        await db.flush()

        e1 = WorkflowEdge(project_id=DEMO_PROJECT_1, source_node_id=n1.id, target_node_id=n2.id, edge_type="default")
        e2 = WorkflowEdge(project_id=DEMO_PROJECT_1, source_node_id=n2.id, target_node_id=n3.id, edge_type="default")
        e3 = WorkflowEdge(project_id=DEMO_PROJECT_1, source_node_id=n3.id, target_node_id=n4.id, edge_type="dependency")
        e4 = WorkflowEdge(project_id=DEMO_PROJECT_1, source_node_id=n5.id, target_node_id=n3.id, edge_type="evidence")
        db.add_all([e1, e2, e3, e4])

        # ── General conversation (no project) ─────────────────────────────────
        conv_general = Conversation(
            id="demo-conv-general",
            user_id=DEMO_USER_ID,
            title="What is gradient descent?",
            mode="teaching",
            is_demo=True,
        )
        db.add(conv_general)
        await db.flush()

        mg1 = Message(
            conversation_id="demo-conv-general",
            role="user",
            content="Can you explain gradient descent simply?",
            is_demo=True,
        )
        db.add(mg1)
        await db.flush()

        mg2 = Message(
            conversation_id="demo-conv-general",
            role="assistant",
            content="""## Gradient Descent – Simple Explanation

Imagine you're hiking on a hilly landscape and want to reach the lowest valley.

**The idea:** At every step, look around you and move in the direction that goes downhill the fastest.

**In machine learning:**
- The "landscape" is your loss function (how wrong your model is)
- Each "step" is an update to your model's parameters
- The "downhill direction" is the gradient — a mathematical arrow pointing toward higher error
- You move **opposite** to the gradient to reduce error

**The formula:**
```
new_weight = old_weight - learning_rate × gradient
```

The **learning rate** controls step size. Too large: you overshoot the valley. Too small: you move too slowly.

**Types:**
- **Batch gradient descent:** Use all data each step (slow but stable)
- **Stochastic (SGD):** Use one random sample each step (noisy but fast)
- **Mini-batch:** Use a small batch (best of both worlds)
""" + DEMO_NOTICE,
            is_demo=True,
        )
        db.add(mg2)

        await db.commit()


if __name__ == "__main__":
    import asyncio
    asyncio.run(seed_demo_data())
